stages:
  - test
  - package
  - integracion1
  - logintegracion1
  - produccion1
  - produccion2
  - logproduccion1
  - logproduccion2
test:
  stage: test
  tags:
    - maven
    - jdk11
  only:
    - integracion
    - produccion
  script:
    - echo "Testing PCR-Covid19"
    - mvn test  
package:
  stage: package
  tags: 
    - maven
    - jdk11
  only:
    - integracion
    - produccion
  dependencies:
    - test
  artifacts:
    paths:
      - target/covid19.jar
  script:
    - echo "Construyendo proyecto covid19"
    - mvn -Dmaven.test.skip=true package -U 
integracion1:
  stage: integracion1
  tags:
    - ssh
  only:
    - integracion
  dependencies:
    - package
  script:
    - echo 'Desplegando covid19 en servidor de integración'
    - scp target/covid19.jar ades@$SERVIDOR_INT_COVID19_1:/home/ades
    - ssh ades@$SERVIDOR_INT_COVID19_1 'sudo rm -f /opt/covid19/covid19.old.jar'
    - ssh ades@$SERVIDOR_INT_COVID19_1 'sudo mv /opt/covid19/covid19.jar /opt/covid19/covid19.old.jar'
    - ssh ades@$SERVIDOR_INT_COVID19_1 'sudo cp /home/ades/covid19.jar /opt/covid19/'
    - ssh ades@$SERVIDOR_INT_COVID19_1 'sudo systemctl restart covid19'
logIntegracion1:
  stage: logintegracion1
  tags:
    - ssh
  only:
    - integracion
  dependencies:
    - integracion1
  script:
    - echo 'Visualizando log servidor integración 1'
    - ssh ades@$SERVIDOR_INT_COVID19_1 'sudo tail -n 500 /opt/covid19/logs/covid19.log'
  when: manual 
produccion1:
  stage: produccion1
  tags:
    - ssh
  only:
    - produccion
  dependencies:
    - package
  script:
    - echo 'Desplegando covid19 en servidor de produccion 1'
    - scp target/covid19.jar ades@$SERVIDOR_PROD_COVID19_1:/home/ades
    - ssh ades@$SERVIDOR_PROD_COVID19_1 'sudo rm -f /opt/covid19/covid19.old.jar'
    - ssh ades@$SERVIDOR_PROD_COVID19_1 'sudo mv /opt/covid19/covid19.jar /opt/covid19/covid19.old.jar'
    - ssh ades@$SERVIDOR_PROD_COVID19_1 'sudo cp /home/ades/covid19.jar /opt/covid19/'
    - ssh ades@$SERVIDOR_PROD_COVID19_1 'sudo systemctl restart covid19'
produccion2:
  stage: produccion2
  tags:
    - ssh
  only:
    - produccion
  dependencies:
    - package
  script:
    - echo 'Desplegando covid19 en servidor de produccion 2'
    - scp target/covid19.jar ades@$SERVIDOR_PROD_COVID19_2:/home/ades
    - ssh ades@$SERVIDOR_PROD_COVID19_2 'sudo rm -f /opt/covid19/covid19.old.jar'
    - ssh ades@$SERVIDOR_PROD_COVID19_2 'sudo mv /opt/covid19/covid19.jar /opt/covid19/covid19.old.jar'
    - ssh ades@$SERVIDOR_PROD_COVID19_2 'sudo cp /home/ades/covid19.jar /opt/covid19/'
    - ssh ades@$SERVIDOR_PROD_COVID19_2 'sudo systemctl restart covid19'
logProduccion1:
  stage: logproduccion1
  tags:
    - ssh
  only:
    - produccion
  dependencies:
    - produccion1
  script:
    - echo 'Visualizando log servidor produccion 1'
    - ssh ades@$SERVIDOR_PROD_COVID19_1 'sudo tail -n 500 /opt/covid19/logs/covid19.log'
  when: manual   
logProduccion2:
  stage: logproduccion2
  tags:
    - ssh
  only:
    - produccion
  dependencies:
    - produccion2
  script:
    - echo 'Visualizando log servidor produccion 2'
    - ssh ades@$SERVIDOR_PROD_COVID19_2 'sudo tail -n 500 /opt/covid19/logs/covid19.log'
  when: manual   