stages:
  - test
  - package
  - integracion
  - logintegracion
test:
  stage: test
  tags:
    - maven
    - jdk11
  only:
    - integracion
  script:
    - echo "Testing PCR-Covid19"
    - mvn test  
package:
  stage: package
  tags: 
    - maven
    - jdk11
  only:
    - integracion
  dependencies:
    - test
  artifacts:
    paths:
      - target/complupcr.jar
  script:
    - echo "Construyendo proyecto complupcr"
    - mvn -Dmaven.test.skip=true package -U 
integracion1:
  stage: integracion
  tags:
    - ssh
  only:
    - integracion
  dependencies:
    - package
  script:
    - echo 'Desplegando complupcr en servidor de integración 1'
    - scp target/complupcr.jar complupcr@$SERVIDOR_INT_JDK11_1:/home/complupcr
    - ssh complupcr@$SERVIDOR_INT_JDK11_1 'sudo cp /home/complupcr/complupcr.jar /opt/covid19/'
    - ssh complupcr@$SERVIDOR_INT_JDK11_1 'sudo systemctl restart complupcr'
  when: manual
logIntegracion1:
  stage: logintegracion
  tags:
    - ssh
  only:
    - integracion
  dependencies:
    - integracion1
  script:
    - echo 'Visualizando log servidor integración 1'
    - ssh complupcr@$SERVIDOR_INT_JDK11_1 'sudo tail -n 500 /opt/covid19/logs/covid19.log'
  when: manual 
