package es.ucm.pcr.modelo.orm;
// Generated 25 mar. 2020 19:09:36 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centro generated by hbm2java
 */
@Entity
@Table(name = "centro")
public class Centro implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String codCentro;
	private String telefono;
	private String email;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Muestra> muestras = new HashSet<Muestra>(0);

	public Centro() {
	}

	public Centro(String nombre, String codCentro) {
		this.nombre = nombre;
		this.codCentro = codCentro;
	}

	public Centro(String nombre, String codCentro, String telefono, String email, Set<Usuario> usuarios,
			Set<Muestra> muestras) {
		this.nombre = nombre;
		this.codCentro = codCentro;
		this.telefono = telefono;
		this.email = email;
		this.usuarios = usuarios;
		this.muestras = muestras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codCentro", nullable = false, length = 25)
	public String getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(String codCentro) {
		this.codCentro = codCentro;
	}

	@Column(name = "telefono", length = 25)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set<Muestra> getMuestras() {
		return this.muestras;
	}

	public void setMuestras(Set<Muestra> muestras) {
		this.muestras = muestras;
	}

}
