/*************************************
COMPLUPCR implements a process for obtaining PCR results from a sample
until the final report of the analysis results. It allows to combine
multiple laboratories and coordinate the work of analysists working
remotely, besides tracing the whole process.

Copyright (C) 2020  Universidad Complutense de Madrid

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
**************************************/

package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento")
public class Documento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7751336283838591859L;
	private Integer id;
	private Centro centro;
	private LaboratorioCentro laboratorioCentro;
	private LaboratorioVisavet laboratorioVisavet;
	private Muestra muestra;
	private PlacaLaboratorio placaLaboratorio;
	private PlacaVisavet placaVisavet;
	private Usuario usuario;
	private String nombre;
	private String tipo;
	private byte[] fichero;
	private Integer tamanoDocumento;
	private Date fechaDocumento;

	public Documento() {
	}

	public Documento(String nombre, String tipo, byte[] fichero) {
		this.nombre = nombre;
		this.tipo = tipo;
		this.fichero = fichero;
	}

	public Documento(Centro centro, LaboratorioCentro laboratorioCentro, LaboratorioVisavet laboratorioVisavet,
			Muestra muestra, PlacaLaboratorio placaLaboratorio, PlacaVisavet placaVisavet, Usuario usuario,
			String nombre, String tipo, byte[] fichero, Integer tamanoDocumento, Date fechaDocumento) {
		this.centro = centro;
		this.laboratorioCentro = laboratorioCentro;
		this.laboratorioVisavet = laboratorioVisavet;
		this.muestra = muestra;
		this.placaLaboratorio = placaLaboratorio;
		this.placaVisavet = placaVisavet;
		this.usuario = usuario;
		this.nombre = nombre;
		this.tipo = tipo;
		this.fichero = fichero;
		this.tamanoDocumento = tamanoDocumento;
		this.fechaDocumento = fechaDocumento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idCentro")
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne
	@JoinColumn(name = "idLaboratorioCentro")
	public LaboratorioCentro getLaboratorioCentro() {
		return this.laboratorioCentro;
	}

	public void setLaboratorioCentro(LaboratorioCentro laboratorioCentro) {
		this.laboratorioCentro = laboratorioCentro;
	}

	@ManyToOne
	@JoinColumn(name = "idLaboratorioVisavet")
	public LaboratorioVisavet getLaboratorioVisavet() {
		return this.laboratorioVisavet;
	}

	public void setLaboratorioVisavet(LaboratorioVisavet laboratorioVisavet) {
		this.laboratorioVisavet = laboratorioVisavet;
	}

	@ManyToOne
	@JoinColumn(name = "idMuestra")
	public Muestra getMuestra() {
		return this.muestra;
	}

	public void setMuestra(Muestra muestra) {
		this.muestra = muestra;
	}

	@ManyToOne
	@JoinColumn(name = "IdPlacaLaboratorio")
	public PlacaLaboratorio getPlacaLaboratorio() {
		return this.placaLaboratorio;
	}

	public void setPlacaLaboratorio(PlacaLaboratorio placaLaboratorio) {
		this.placaLaboratorio = placaLaboratorio;
	}

	@ManyToOne
	@JoinColumn(name = "idPlacaVisavet")
	public PlacaVisavet getPlacaVisavet() {
		return this.placaVisavet;
	}

	public void setPlacaVisavet(PlacaVisavet placaVisavet) {
		this.placaVisavet = placaVisavet;
	}

	@ManyToOne
	@JoinColumn(name = "idUsuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo", length = 3)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "fichero", nullable = false)
	@Lob
	public byte[] getFichero() {
		return this.fichero;
	}

	public void setFichero(byte[] fichero) {
		this.fichero = fichero;
	}

	@Column(name = "tamanoDocumento")
	public Integer getTamanoDocumento() {
		return this.tamanoDocumento;
	}

	public void setTamanoDocumento(Integer tamanoDocumento) {
		this.tamanoDocumento = tamanoDocumento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaDocumento", length = 19)
	public Date getFechaDocumento() {
		return this.fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}

}
