package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 12:25:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoLote generated by hbm2java
 */
@Entity
@Table(name = "estadoLote")
public class EstadoLote implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set<Lote> lotes = new HashSet<Lote>(0);

	public EstadoLote() {
	}

	public EstadoLote(String descripcion) {
		this.descripcion = descripcion;
	}

	public EstadoLote(String descripcion, Set<Lote> lotes) {
		this.descripcion = descripcion;
		this.lotes = lotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoLote")
	public Set<Lote> getLotes() {
		return this.lotes;
	}

	public void setLotes(Set<Lote> lotes) {
		this.lotes = lotes;
	}

}
