package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoPlacaLaboratorio generated by hbm2java
 */
@Entity
@Table(name = "estadoPlacaLaboratorio", catalog = "dcovid")
public class EstadoPlacaLaboratorio implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set<PlacaLaboratorio> placaLaboratorios = new HashSet<PlacaLaboratorio>(0);

	public EstadoPlacaLaboratorio() {
	}

	public EstadoPlacaLaboratorio(String descripcion) {
		this.descripcion = descripcion;
	}

	public EstadoPlacaLaboratorio(String descripcion, Set<PlacaLaboratorio> placaLaboratorios) {
		this.descripcion = descripcion;
		this.placaLaboratorios = placaLaboratorios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoPlacaLaboratorio")
	public Set<PlacaLaboratorio> getPlacaLaboratorios() {
		return this.placaLaboratorios;
	}

	public void setPlacaLaboratorios(Set<PlacaLaboratorio> placaLaboratorios) {
		this.placaLaboratorios = placaLaboratorios;
	}

}
