package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoPlacaVisavet generated by hbm2java
 */
@Entity
@Table(name = "estadoPlacaVisavet")
public class EstadoPlacaVisavet implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set<PlacaVisavet> placaVisavets = new HashSet<PlacaVisavet>(0);

	public EstadoPlacaVisavet() {
	}

	public EstadoPlacaVisavet(String descripcion) {
		this.descripcion = descripcion;
	}

	public EstadoPlacaVisavet(String descripcion, Set<PlacaVisavet> placaVisavets) {
		this.descripcion = descripcion;
		this.placaVisavets = placaVisavets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoPlacaVisavet")
	public Set<PlacaVisavet> getPlacaVisavets() {
		return this.placaVisavets;
	}

	public void setPlacaVisavets(Set<PlacaVisavet> placaVisavets) {
		this.placaVisavets = placaVisavets;
	}

}
