package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name = "lote")
public class Lote implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5514642009608260822L;
	private int id;
	private Centro centro;
	private EstadoLote estadoLote;
	private PlacaVisavet placaVisavet;
	private String numeroLote;
	private Date fechaEnvio;
	private int capacidad;
	private LaboratorioVisavet laboratorioVisavet;
	private Set<Muestra> muestras = new HashSet<Muestra>(0);

	public Lote() {
	}
	
	public Lote(int id) {
		super();
		this.id = id;
	}

	public Lote(int id, Centro centro, EstadoLote estadoLote, String numeroLote, int capacidad) {
		this.id = id;
		this.centro = centro;
		this.estadoLote = estadoLote;
		this.numeroLote = numeroLote;
		this.capacidad = capacidad;
	}

	public Lote(int id, Centro centro, EstadoLote estadoLote, PlacaVisavet placaVisavet, String numeroLote,
			Date fechaEnvio, int capacidad, Set<Muestra> muestras) {
		this.id = id;
		this.centro = centro;
		this.estadoLote = estadoLote;
		this.placaVisavet = placaVisavet;
		this.numeroLote = numeroLote;
		this.fechaEnvio = fechaEnvio;
		this.capacidad = capacidad;
		this.muestras = muestras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idCentro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstadoLote", nullable = false)
	public EstadoLote getEstadoLote() {
		return this.estadoLote;
	}

	public void setEstadoLote(EstadoLote estadoLote) {
		this.estadoLote = estadoLote;
	}
	
	@ManyToOne
	@JoinColumn(name = "idLaboratorioVisavet", nullable = true)
	public LaboratorioVisavet getLaboratorioVisavet() {
		return laboratorioVisavet;
	}

	public void setLaboratorioVisavet(LaboratorioVisavet laboratorioVisavet) {
		this.laboratorioVisavet = laboratorioVisavet;
	}

	@ManyToOne
	@JoinColumn(name = "idPlacaVisavet")
	public PlacaVisavet getPlacaVisavet() {
		return this.placaVisavet;
	}

	public void setPlacaVisavet(PlacaVisavet placaVisavet) {
		this.placaVisavet = placaVisavet;
	}

	@Column(name = "numeroLote", nullable = false, length = 100)
	public String getNumeroLote() {
		return this.numeroLote;
	}

	public void setNumeroLote(String numeroLote) {
		this.numeroLote = numeroLote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEnvio", length = 10)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Column(name = "capacidad", nullable = false)
	public int getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(int capacidad) {
		this.capacidad = capacidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lote")
	public Set<Muestra> getMuestras() {
		return this.muestras;
	}

	public void setMuestras(Set<Muestra> muestras) {
		this.muestras = muestras;
	}

}
