package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 12:25:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name = "lote")
public class Lote implements java.io.Serializable {

	private int id;
	private Centro centro;
	private EstadoLote estadoLote;
	private String numeroLote;
	private String fechaEnvio;
	private Integer capacidad;
	private Set<Muestra> muestras = new HashSet<Muestra>(0);

	public Lote() {
	}

	public Lote(int id, Centro centro, EstadoLote estadoLote, String numeroLote) {
		this.id = id;
		this.centro = centro;
		this.estadoLote = estadoLote;
		this.numeroLote = numeroLote;
	}

	public Lote(int id, Centro centro, EstadoLote estadoLote, String numeroLote, String fechaEnvio,
			Set<Muestra> muestras) {
		this.id = id;
		this.centro = centro;
		this.estadoLote = estadoLote;
		this.numeroLote = numeroLote;
		this.fechaEnvio = fechaEnvio;
		this.muestras = muestras;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idCentro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne
	@JoinColumn(name = "idEstadoLote", nullable = false)
	public EstadoLote getEstadoLote() {
		return this.estadoLote;
	}

	public void setEstadoLote(EstadoLote estadoLote) {
		this.estadoLote = estadoLote;
	}

	@Column(name = "numeroLote", nullable = false, length = 100)
	public String getNumeroLote() {
		return this.numeroLote;
	}

	public void setNumeroLote(String numeroLote) {
		this.numeroLote = numeroLote;
	}

	@Column(name = "fechaEnvio", length = 45)
	public String getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(String fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}
	
	@Column(name = "capacidad", nullable = false)
	public Integer getCapacidad() {
		return capacidad;
	}

	public void setCapacidad(Integer capacidad) {
		this.capacidad = capacidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lote")
	public Set<Muestra> getMuestras() {
		return this.muestras;
	}

	public void setMuestras(Set<Muestra> muestras) {
		this.muestras = muestras;
	}

}
