package es.ucm.pcr.modelo.orm;
// Generated 25 mar. 2020 19:09:36 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Muestra generated by hbm2java
 */
@Entity
@Table(name = "muestra")
public class Muestra implements java.io.Serializable {

	private Integer id;
	private Centro centro;
	private String etiqueta;
	private String tipoMuestra;
	private Date fechaEntrada;
	private Date fechaEnvio;
	private Date fechaResultado;
	private String refInterna;
	private String resultado;
	private Integer idEstado;
	private int idLote;
	private String nhc;
	private boolean recogerDatosNotif;
	private boolean avisosAuto;
	private String nombreApellidos;
	private String correo;
	private String telefono;
	private boolean avisoSms;
	private Date fechaNotificacion;

	public Muestra() {
	}

	public Muestra(Centro centro, String etiqueta, String tipoMuestra, int idLote, boolean recogerDatosNotif,
			boolean avisosAuto, String nombreApellidos, boolean avisoSms) {
		this.centro = centro;
		this.etiqueta = etiqueta;
		this.tipoMuestra = tipoMuestra;
		this.idLote = idLote;
		this.recogerDatosNotif = recogerDatosNotif;
		this.avisosAuto = avisosAuto;
		this.nombreApellidos = nombreApellidos;
		this.avisoSms = avisoSms;
	}

	public Muestra(Centro centro, String etiqueta, String tipoMuestra, Date fechaEntrada, Date fechaEnvio,
			Date fechaResultado, String refInterna, String resultado, Integer idEstado, int idLote, String nhc,
			boolean recogerDatosNotif, boolean avisosAuto, String nombreApellidos, String correo, String telefono,
			boolean avisoSms, Date fechaNotificacion) {
		this.centro = centro;
		this.etiqueta = etiqueta;
		this.tipoMuestra = tipoMuestra;
		this.fechaEntrada = fechaEntrada;
		this.fechaEnvio = fechaEnvio;
		this.fechaResultado = fechaResultado;
		this.refInterna = refInterna;
		this.resultado = resultado;
		this.idEstado = idEstado;
		this.idLote = idLote;
		this.nhc = nhc;
		this.recogerDatosNotif = recogerDatosNotif;
		this.avisosAuto = avisosAuto;
		this.nombreApellidos = nombreApellidos;
		this.correo = correo;
		this.telefono = telefono;
		this.avisoSms = avisoSms;
		this.fechaNotificacion = fechaNotificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCentro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@Column(name = "etiqueta", nullable = false, length = 100)
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	@Column(name = "tipoMuestra", nullable = false, length = 2)
	public String getTipoMuestra() {
		return this.tipoMuestra;
	}

	public void setTipoMuestra(String tipoMuestra) {
		this.tipoMuestra = tipoMuestra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEntrada", length = 19)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEnvio", length = 19)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaResultado", length = 19)
	public Date getFechaResultado() {
		return this.fechaResultado;
	}

	public void setFechaResultado(Date fechaResultado) {
		this.fechaResultado = fechaResultado;
	}

	@Column(name = "refInterna", length = 100)
	public String getRefInterna() {
		return this.refInterna;
	}

	public void setRefInterna(String refInterna) {
		this.refInterna = refInterna;
	}

	@Column(name = "resultado", length = 25)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Column(name = "idEstado")
	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "idLote", nullable = false)
	public int getIdLote() {
		return this.idLote;
	}

	public void setIdLote(int idLote) {
		this.idLote = idLote;
	}

	@Column(name = "NHC", length = 100)
	public String getNhc() {
		return this.nhc;
	}

	public void setNhc(String nhc) {
		this.nhc = nhc;
	}

	@Column(name = "recogerDatosNotif", nullable = false)
	public boolean isRecogerDatosNotif() {
		return this.recogerDatosNotif;
	}

	public void setRecogerDatosNotif(boolean recogerDatosNotif) {
		this.recogerDatosNotif = recogerDatosNotif;
	}

	@Column(name = "avisosAuto", nullable = false)
	public boolean isAvisosAuto() {
		return this.avisosAuto;
	}

	public void setAvisosAuto(boolean avisosAuto) {
		this.avisosAuto = avisosAuto;
	}

	@Column(name = "nombreApellidos", nullable = false, length = 200)
	public String getNombreApellidos() {
		return this.nombreApellidos;
	}

	public void setNombreApellidos(String nombreApellidos) {
		this.nombreApellidos = nombreApellidos;
	}

	@Column(name = "correo", length = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "telefono", length = 25)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "avisoSMS", nullable = false)
	public boolean isAvisoSms() {
		return this.avisoSms;
	}

	public void setAvisoSms(boolean avisoSms) {
		this.avisoSms = avisoSms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaNotificacion", length = 19)
	public Date getFechaNotificacion() {
		return this.fechaNotificacion;
	}

	public void setFechaNotificacion(Date fechaNotificacion) {
		this.fechaNotificacion = fechaNotificacion;
	}

}
