package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Muestra generated by hbm2java
 */
@Entity
@Table(name = "muestra")
public class Muestra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4671038846103227678L;
	private Integer id;
	private Centro centro;
	private EstadoMuestra estadoMuestra;
	private Lote lote;
	private PlacaVisavet placaVisavet;
	private PlacaLaboratorio placaLaboratorio;
	private String etiqueta;
	private String tipoMuestra;
	private Date fechaEntrada;
	private Date fechaEnvio;
	private Date fechaResultado;
	private String refInternaVisavet;
	private String resultado;
	private Date fechaAsignada;
	private Date fechaNotificacion;
	private Set<UsuarioMuestra> usuarioMuestras = new HashSet<UsuarioMuestra>(0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Paciente paciente;
	private Integer numerodeAnalistasAsignados;
	private Set<LogMuestras> logMuestra = new HashSet<LogMuestras>();

	public Muestra() {
	}

	public Muestra(Integer id) {
		super();
		this.id = id;
	}

	public Muestra(Centro centro, EstadoMuestra estadoMuestra, String etiqueta, String tipoMuestra) {
		this.centro = centro;
		this.estadoMuestra = estadoMuestra;
		this.etiqueta = etiqueta;
		this.tipoMuestra = tipoMuestra;
	}

	public Muestra(Centro centro, EstadoMuestra estadoMuestra, Lote lote,PlacaVisavet  placaVisavet, PlacaLaboratorio  placaLaboratorio , String etiqueta, String tipoMuestra,
			Date fechaEntrada, Date fechaEnvio, Date fechaResultado, String refInternaVisavet, String resultado,
			Date fechaAsignada, Date fechaNotificacion, Set<UsuarioMuestra> usuarioMuestras,
			Set<Documento> documentos, Paciente paciente) {
		this.centro = centro;
		this.estadoMuestra = estadoMuestra;
		this.lote = lote;
		this.placaVisavet = placaVisavet; 
		this.placaLaboratorio = placaLaboratorio ;
		this.etiqueta = etiqueta;
		this.tipoMuestra = tipoMuestra;
		this.fechaEntrada = fechaEntrada;
		this.fechaEnvio = fechaEnvio;
		this.fechaResultado = fechaResultado;
		this.refInternaVisavet = refInternaVisavet;
		this.resultado = resultado;
		this.fechaAsignada = fechaAsignada;
		this.fechaNotificacion = fechaNotificacion;
		this.usuarioMuestras = usuarioMuestras;
		this.documentos = documentos;
		this.paciente = paciente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idCentro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne
	@JoinColumn(name = "idEstadoMuestra", nullable = false)
	public EstadoMuestra getEstadoMuestra() {
		return this.estadoMuestra;
	}

	public void setEstadoMuestra(EstadoMuestra estadoMuestra) {
		this.estadoMuestra = estadoMuestra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLote")
	public Lote getLote() {
		return this.lote;
	}

	public void setLote(Lote lote) {
		this.lote = lote;
	}
	@ManyToOne
	@JoinColumn(name = "idPlacaVisavet")
	public PlacaVisavet getPlacaVisavet() {
		return this.placaVisavet;
	}

	public void setPlacaVisavet(PlacaVisavet placaVisavet) {
		this.placaVisavet = placaVisavet;
	}
	
	@ManyToOne
	@JoinColumn(name = "idPlacaLaboratorio")
	public PlacaLaboratorio getPlacaLaboratorio() {
		return this.placaLaboratorio;
	}

	public void setPlacaLaboratorio(PlacaLaboratorio placaLaboratorio) {
		this.placaLaboratorio = placaLaboratorio;
	}
	@Column(name = "etiqueta", nullable = false, length = 100)
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	@Column(name = "tipoMuestra", nullable = false, length = 2)
	public String getTipoMuestra() {
		return this.tipoMuestra;
	}

	public void setTipoMuestra(String tipoMuestra) {
		this.tipoMuestra = tipoMuestra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEntrada", length = 19)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEnvio", length = 19)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaResultado", length = 19)
	public Date getFechaResultado() {
		return this.fechaResultado;
	}

	public void setFechaResultado(Date fechaResultado) {
		this.fechaResultado = fechaResultado;
	}

	@Column(name = "refInternaVisavet", length = 100)
	public String getRefInternaVisavet() {
		return this.refInternaVisavet;
	}

	public void setRefInternaVisavet(String refInternaVisavet) {
		this.refInternaVisavet = refInternaVisavet;
	}

	@Column(name = "resultado", length = 25)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaAsignada", length = 19)	
	public Date getFechaAsignada() {
		return this.fechaAsignada;
	}

	public void setFechaAsignada(Date fechaAsignada) {
		this.fechaAsignada = fechaAsignada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaNotificacion", length = 19)
	public Date getFechaNotificacion() {
		return this.fechaNotificacion;
	}

	public void setFechaNotificacion(Date fechaNotificacion) {
		this.fechaNotificacion = fechaNotificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "muestra")
	public Set<UsuarioMuestra> getUsuarioMuestras() {
		return this.usuarioMuestras;
	}

	public void setUsuarioMuestras(Set<UsuarioMuestra> usuarioMuestras) {
		this.usuarioMuestras = usuarioMuestras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "muestra")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToOne(fetch = FetchType.LAZY,
            cascade =  CascadeType.ALL,
            mappedBy = "muestra")
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Column(name = "numerodeAnalistasAsignados")	
	public Integer getNumerodeAnalistasAsignados() {
		return numerodeAnalistasAsignados;
	}

	public void setNumerodeAnalistasAsignados(Integer numerodeAnalistasAsignados) {
		this.numerodeAnalistasAsignados = numerodeAnalistasAsignados;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "muestra")
	public Set<LogMuestras> getLogMuestra() {
		return this.logMuestra;
	}

	public void setLogMuestra(Set<LogMuestras> logMuestra) {
		this.logMuestra = logMuestra;
	}

	@Override
	public String toString() {
		return "Muestra [id=" + id + ", centro=" + centro + ", estadoMuestra=" + estadoMuestra + 
				", etiqueta=" + etiqueta + ", tipoMuestra=" + tipoMuestra + ", resultado="
				+ resultado + ", usuarioMuestras=" + usuarioMuestras + ", numerodeAnalistasAsignados="
				+ numerodeAnalistasAsignados + "]";
	}
	
	

}
