package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PasswordResetToken generated by hbm2java
 */
@Entity
@Table(name = "passwordResetToken", catalog = "dcovid")
public class PasswordResetToken implements java.io.Serializable {

	private Integer idpasswordResetToken;
	private Usuario usuario;
	private String token;

	public PasswordResetToken() {
	}

	public PasswordResetToken(Usuario usuario) {
		this.usuario = usuario;
	}

	public PasswordResetToken(Usuario usuario, String token) {
		this.usuario = usuario;
		this.token = token;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpasswordResetToken", unique = true, nullable = false)
	public Integer getIdpasswordResetToken() {
		return this.idpasswordResetToken;
	}

	public void setIdpasswordResetToken(Integer idpasswordResetToken) {
		this.idpasswordResetToken = idpasswordResetToken;
	}

	@ManyToOne
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "token", length = 100)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
