package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlacaVisavetPlacaLaboratorio generated by hbm2java
 */
@Entity
@Table(name = "placaVisavet_placaLaboratorio", catalog = "dcovid")
public class PlacaVisavetPlacaLaboratorio implements java.io.Serializable {

	private Integer id;
	private PlacaLaboratorio placaLaboratorio;
	private PlacaVisavet placaVisavet;

	public PlacaVisavetPlacaLaboratorio() {
	}

	public PlacaVisavetPlacaLaboratorio(PlacaLaboratorio placaLaboratorio, PlacaVisavet placaVisavet) {
		this.placaLaboratorio = placaLaboratorio;
		this.placaVisavet = placaVisavet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idplacaLaboratorio", nullable = false)
	public PlacaLaboratorio getPlacaLaboratorio() {
		return this.placaLaboratorio;
	}

	public void setPlacaLaboratorio(PlacaLaboratorio placaLaboratorio) {
		this.placaLaboratorio = placaLaboratorio;
	}

	@ManyToOne
	@JoinColumn(name = "idplacaVisavet", nullable = false)
	public PlacaVisavet getPlacaVisavet() {
		return this.placaVisavet;
	}

	public void setPlacaVisavet(PlacaVisavet placaVisavet) {
		this.placaVisavet = placaVisavet;
	}

}
