/*************************************
COMPLUPCR implements a process for obtaining PCR results from a sample
until the final report of the analysis results. It allows to combine
multiple laboratories and coordinate the work of analysists working
remotely, besides tracing the whole process.

Copyright (C) 2020  Universidad Complutense de Madrid

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
**************************************/

package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlacaLaboratorio generated by hbm2java
 */
@Entity
@Table(name = "placaLaboratorio")
public class PlacaLaboratorio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8411367653815958258L;
	private int id;
	private EstadoPlacaLaboratorio estadoPlacaLaboratorio;
	private LaboratorioCentro laboratorioCentro;
	private String numeromuestras;
	private Date fechaCreacion;
	private Date fechaListaAnalisis;
	private Date fechaAsignadaJefe;
	private Set<PlacaVisavetPlacaLaboratorio> placaVisavetPlacaLaboratorios = new HashSet<PlacaVisavetPlacaLaboratorio>(
			0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Usuario usuario; //un jefe coge la placa para asignar sus muestras a los analistas
	private Set<Muestra> muestras = new HashSet<Muestra>(0);
	private Equipo equipo;
	

	public PlacaLaboratorio() {
	}
	
	public PlacaLaboratorio(int id) {
		super();
		this.id = id;
	}

	public PlacaLaboratorio(int id, EstadoPlacaLaboratorio estadoPlacaLaboratorio,
			LaboratorioCentro laboratorioCentro) {
		this.id = id;
		this.estadoPlacaLaboratorio = estadoPlacaLaboratorio;
		this.laboratorioCentro = laboratorioCentro;
	}

	public PlacaLaboratorio(int id, EstadoPlacaLaboratorio estadoPlacaLaboratorio, LaboratorioCentro laboratorioCentro,
			String numeromuestras, Set<PlacaVisavetPlacaLaboratorio> placaVisavetPlacaLaboratorios,
			Set<Documento> documentos) {
		this.id = id;
		this.estadoPlacaLaboratorio = estadoPlacaLaboratorio;
		this.laboratorioCentro = laboratorioCentro;
		this.numeromuestras = numeromuestras;
		this.placaVisavetPlacaLaboratorios = placaVisavetPlacaLaboratorios;
		this.documentos = documentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idEstadoPlacaLaboratorio", nullable = false)
	public EstadoPlacaLaboratorio getEstadoPlacaLaboratorio() {
		return this.estadoPlacaLaboratorio;
	}

	public void setEstadoPlacaLaboratorio(EstadoPlacaLaboratorio estadoPlacaLaboratorio) {
		this.estadoPlacaLaboratorio = estadoPlacaLaboratorio;
	}

	@ManyToOne
	@JoinColumn(name = "idEquipo", nullable = true)
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}
	
	@ManyToOne
	@JoinColumn(name = "idLaboratorioCentro", nullable = false)
	public LaboratorioCentro getLaboratorioCentro() {
		return this.laboratorioCentro;
	}

	public void setLaboratorioCentro(LaboratorioCentro laboratorioCentro) {
		this.laboratorioCentro = laboratorioCentro;
	}

	@Column(name = "numeromuestras", length = 45)
	public String getNumeromuestras() {
		return this.numeromuestras;
	}

	public void setNumeromuestras(String numeromuestras) {
		this.numeromuestras = numeromuestras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaLaboratorio")
	public Set<PlacaVisavetPlacaLaboratorio> getPlacaVisavetPlacaLaboratorios() {
		return this.placaVisavetPlacaLaboratorios;
	}

	public void setPlacaVisavetPlacaLaboratorios(Set<PlacaVisavetPlacaLaboratorio> placaVisavetPlacaLaboratorios) {
		this.placaVisavetPlacaLaboratorios = placaVisavetPlacaLaboratorios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaLaboratorio")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}
	
	
	@ManyToOne
	@JoinColumn(name = "idUsuario")
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreaccion", length = 10)
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaListaAnalisis", length = 10)
	public Date getFechaListaAnalisis() {
		return fechaListaAnalisis;
	}

	public void setFechaListaAnalisis(Date fechaListaAnalisis) {
		this.fechaListaAnalisis = fechaListaAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaAsignadaJefe", length = 10)
	public Date getFechaAsignadaJefe() {
		return fechaAsignadaJefe;
	}

	public void setFechaAsignadaJefe(Date fechaAsignadaJefe) {
		this.fechaAsignadaJefe = fechaAsignadaJefe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaLaboratorio")
	public Set<Muestra> getMuestras() {
		return this.muestras;
	}

	public void setMuestras(Set<Muestra> muestras) {
		this.muestras = muestras;
	}
	

	@Override
	public String toString() {
		return "PlacaLaboratorio [id=" + id + ", estadoPlacaLaboratorio=" + estadoPlacaLaboratorio
				+ ", laboratorioCentro=" + laboratorioCentro + ", numeromuestras=" + numeromuestras + ", fechaCreacion="
				+ fechaCreacion + ", placaVisavetPlacaLaboratorios=" + placaVisavetPlacaLaboratorios + ", documentos="
				+ documentos + ", usuario=" + usuario + ", muestras=" + muestras + "]";
	}
	
	
}
