package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 12:25:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlacaLaboratorio generated by hbm2java
 */
@Entity
@Table(name = "placaLaboratorio")
public class PlacaLaboratorio implements java.io.Serializable {

	private int id;
	private EstadoPlacaLaboratorio estadoPlacaLaboratorio;
	private LaboratorioCentro laboratorioCentro;
	private String numeromuestras;
	private Set<PlacaVisavetPlacaLaboratorio> placaVisavetPlacaLaboratorios = new HashSet<PlacaVisavetPlacaLaboratorio>(
			0);
	private Set<Documento> documentos = new HashSet<Documento>(0);

	public PlacaLaboratorio() {
	}

	public PlacaLaboratorio(int id, EstadoPlacaLaboratorio estadoPlacaLaboratorio,
			LaboratorioCentro laboratorioCentro) {
		this.id = id;
		this.estadoPlacaLaboratorio = estadoPlacaLaboratorio;
		this.laboratorioCentro = laboratorioCentro;
	}

	public PlacaLaboratorio(int id, EstadoPlacaLaboratorio estadoPlacaLaboratorio, LaboratorioCentro laboratorioCentro,
			String numeromuestras, Set<PlacaVisavetPlacaLaboratorio> placaVisavetPlacaLaboratorios,
			Set<Documento> documentos) {
		this.id = id;
		this.estadoPlacaLaboratorio = estadoPlacaLaboratorio;
		this.laboratorioCentro = laboratorioCentro;
		this.numeromuestras = numeromuestras;
		this.placaVisavetPlacaLaboratorios = placaVisavetPlacaLaboratorios;
		this.documentos = documentos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "idEstadoPlacaLaboratorio", nullable = false)
	public EstadoPlacaLaboratorio getEstadoPlacaLaboratorio() {
		return this.estadoPlacaLaboratorio;
	}

	public void setEstadoPlacaLaboratorio(EstadoPlacaLaboratorio estadoPlacaLaboratorio) {
		this.estadoPlacaLaboratorio = estadoPlacaLaboratorio;
	}

	@ManyToOne
	@JoinColumn(name = "idLaboratorioCentro", nullable = false)
	public LaboratorioCentro getLaboratorioCentro() {
		return this.laboratorioCentro;
	}

	public void setLaboratorioCentro(LaboratorioCentro laboratorioCentro) {
		this.laboratorioCentro = laboratorioCentro;
	}

	@Column(name = "numeromuestras", length = 45)
	public String getNumeromuestras() {
		return this.numeromuestras;
	}

	public void setNumeromuestras(String numeromuestras) {
		this.numeromuestras = numeromuestras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaLaboratorio")
	public Set<PlacaVisavetPlacaLaboratorio> getPlacaVisavetPlacaLaboratorios() {
		return this.placaVisavetPlacaLaboratorios;
	}

	public void setPlacaVisavetPlacaLaboratorios(Set<PlacaVisavetPlacaLaboratorio> placaVisavetPlacaLaboratorios) {
		this.placaVisavetPlacaLaboratorios = placaVisavetPlacaLaboratorios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaLaboratorio")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

}
