package es.ucm.pcr.modelo.orm;
// Generated 30 mar. 2020 17:36:56 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioMuestra generated by hbm2java
 */
@Entity
@Table(name = "usuario_muestra", uniqueConstraints = @UniqueConstraint(columnNames = "idUsuario"))
public class UsuarioMuestra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3347330222060386128L;
	private Integer idUsuarioMuestra;
	private Muestra muestra;
	private Usuario usuario;
	private Date fechaAsignacion;
	private String valoracion;
	private Date fechaValoracion;

	public UsuarioMuestra() {
	}

	public UsuarioMuestra(Muestra muestra, Usuario usuario) {
		this.muestra = muestra;
		this.usuario = usuario;
	}

	public UsuarioMuestra(Muestra muestra, Usuario usuario, Date fechaAsignacion, String valoracion,
			Date fechaValoracion) {
		this.muestra = muestra;
		this.usuario = usuario;
		this.fechaAsignacion = fechaAsignacion;
		this.valoracion = valoracion;
		this.fechaValoracion = fechaValoracion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario_Muestra", unique = true, nullable = false)
	public Integer getIdUsuarioMuestra() {
		return this.idUsuarioMuestra;
	}

	public void setIdUsuarioMuestra(Integer idUsuarioMuestra) {
		this.idUsuarioMuestra = idUsuarioMuestra;
	}

	@ManyToOne
	@JoinColumn(name = "idMuestra", nullable = false)
	public Muestra getMuestra() {
		return this.muestra;
	}

	public void setMuestra(Muestra muestra) {
		this.muestra = muestra;
	}

	@ManyToOne
	@JoinColumn(name = "idUsuario", unique = true, nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaAsignacion", length = 10)
	public Date getFechaAsignacion() {
		return this.fechaAsignacion;
	}

	public void setFechaAsignacion(Date fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}

	@Column(name = "valoracion", length = 45)
	public String getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(String valoracion) {
		this.valoracion = valoracion;
	}

	public Date getFechaValoracion() {
		return fechaValoracion;
	}

	public void setFechaValoracion(Date fechaValoracion) {
		this.fechaValoracion = fechaValoracion;
	}

	
}
